apiVersion: vm.cloudclub.io/v1
kind: Operatingsystems
metadata:
  labels:
    app.kubernetes.io/name: operatingsystems
    app.kubernetes.io/instance: operatingsystems-sample
    app.kubernetes.io/part-of: aviator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: aviator
  name: operatingsystems-sample
spec:
  # TODO(user): Add fields here
