# 1. Test & Build about GO Code
# 2. Push the Container image of Operator Controller to NCP Registry
# 3. Up-to-date kustomization file to cicd repository
name: cicd

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"

      ### Private Docker Registry 정보 가져오기

      ### Docker Build

      ### Docker Registry에 image push

      # kustomize 명령을 가져온다.
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          # kubernetes 설정정보 저장소
          repository: cloud-club/aviator-cicd
          ref: main

      # 새 이미지 버전으로 파일 수정
      - name: Update Kubernetes resources
        run: |
          cd prd
          kustomize edit set image ${{ env.IMAGE_NAME }}:${{ steps.image.outputs.version }}
          cat kustomization.yaml

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          message: "Update image tag ${{ env.IMAGE_NAME }}:${{ steps.image.outputs.version }}"
          repository: cloud-club/aviator-cicd
          branch: master
      # 수정된 파일 commit & push
#      - name: Commit files
#        run: |
#          git config --global user.email "dev-kimdoyoung@github.com"
#          git config --global user.name "dev-kimdoyoung"
#          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cloud-club/aviator-cicd.git
#          git commit -am
#          git push origin master
